import numpy as np
array = np.array([1,2,3,4,5])
print(array)
print(array.ndim)
array2d = np.array([[1,2,3],[4,5,6]])
print(array2d)
print(array2d.size)
print(array2d.ndim)
print(array2d.shape)
print(array2d.dtype)
